//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18449
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvShowQuizz.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TvShowQuizz.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à /Resources/fr/Images/banner@2x.png.
        /// </summary>
        public static string AdBannerReplacement {
            get {
                return ResourceManager.GetString("AdBannerReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à retour.
        /// </summary>
        public static string AppBarBackText {
            get {
                return ResourceManager.GetString("AppBarBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à fermer.
        /// </summary>
        public static string AppBarCloseButton {
            get {
                return ResourceManager.GetString("AppBarCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à actualiser.
        /// </summary>
        public static string AppBarRefreshText {
            get {
                return ResourceManager.GetString("AppBarRefreshText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à TV Show Quizz.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez une langue.
        /// </summary>
        public static string ChooseLanguagePopupText {
            get {
                return ResourceManager.GetString("ChooseLanguagePopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de télécharger un pack. Veuillez vérifier votre connexion de données et réessayer..
        /// </summary>
        public static string DlPackFailed {
            get {
                return ResourceManager.GetString("DlPackFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de télécharger la liste des packs. Veuillez vérifier votre connexion de données et réessayer..
        /// </summary>
        public static string DlPackListFailed {
            get {
                return ResourceManager.GetString("DlPackListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prochaine aide dans #time secondes....
        /// </summary>
        public static string GamePageHelpPopupText {
            get {
                return ResourceManager.GetString("GamePageHelpPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Patience !.
        /// </summary>
        public static string GamePageHelpPopupTitle {
            get {
                return ResourceManager.GetString("GamePageHelpPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trouvé.
        /// </summary>
        public static string GamePageTitleFound {
            get {
                return ResourceManager.GetString("GamePageTitleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide.
        /// </summary>
        public static string HelpPageTitle {
            get {
                return ResourceManager.GetString("HelpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fais défiler toutes les images des series du pack et retrouve leurs titres.
        /// </summary>
        public static string HelpTextPage1 {
            get {
                return ResourceManager.GetString("HelpTextPage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisis le titre à l&apos;aide du clavier et vérifie ta réponse.
        /// </summary>
        public static string HelpTextPage2 {
            get {
                return ResourceManager.GetString("HelpTextPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N&apos;hésite pas à utiliser l&apos;aide ou à faire participer tes amis.
        /// </summary>
        public static string HelpTextPage3 {
            get {
                return ResourceManager.GetString("HelpTextPage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Attention ! Impossible de joindre le serveur. Certaines fonctionalités pourraient ne pas fonctionner ! Veuillez verifier votre connexion de données..
        /// </summary>
        public static string InitNoNetworkMessage {
            get {
                return ResourceManager.GetString("InitNoNetworkMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] level_67 {
            get {
                object obj = ResourceManager.GetObject("level_67", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        public static byte[] level_68 {
            get {
                object obj = ResourceManager.GetObject("level_68", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rejouer.
        /// </summary>
        public static string LevelsPageReinitPack {
            get {
                return ResourceManager.GetString("LevelsPageReinitPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveaux.
        /// </summary>
        public static string LevelsPageTitle {
            get {
                return ResourceManager.GetString("LevelsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement en cours....
        /// </summary>
        public static string LoadingIndicator {
            get {
                return ResourceManager.GetString("LoadingIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cliquez pour commencer à jouer.
        /// </summary>
        public static string MainPageClickToStartPlaying {
            get {
                return ResourceManager.GetString("MainPageClickToStartPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string MainPageOptionsButton {
            get {
                return ResourceManager.GetString("MainPageOptionsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à évaluer.
        /// </summary>
        public static string MainPageRateButton {
            get {
                return ResourceManager.GetString("MainPageRateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à scores.
        /// </summary>
        public static string MainPageScoresButton {
            get {
                return ResourceManager.GetString("MainPageScoresButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminé.
        /// </summary>
        public static string PackagePresenterControlPackTerminated {
            get {
                return ResourceManager.GetString("PackagePresenterControlPackTerminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez fini .
        /// </summary>
        public static string PacksListPageFinishedPacksPart1 {
            get {
                return ResourceManager.GetString("PacksListPageFinishedPacksPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  packs sur .
        /// </summary>
        public static string PacksListPageFinishedPacksPart2 {
            get {
                return ResourceManager.GetString("PacksListPageFinishedPacksPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Niveau.
        /// </summary>
        public static string PacksListPageTitle {
            get {
                return ResourceManager.GetString("PacksListPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        public static string PopupEndPackButtonOk {
            get {
                return ResourceManager.GetString("PopupEndPackButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Packs.
        /// </summary>
        public static string PopupEndPackButtonPacks {
            get {
                return ResourceManager.GetString("PopupEndPackButtonPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez gagné #nbpoints points. .
        /// </summary>
        public static string PopupEndPackMessage {
            get {
                return ResourceManager.GetString("PopupEndPackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pack terminé.
        /// </summary>
        public static string PopupEndPackTitle {
            get {
                return ResourceManager.GetString("PopupEndPackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Installation en cours....
        /// </summary>
        public static string PopupLevelsDownloadInstallationProgress {
            get {
                return ResourceManager.GetString("PopupLevelsDownloadInstallationProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléchargement.
        /// </summary>
        public static string PopupLevelsDownloadMessage {
            get {
                return ResourceManager.GetString("PopupLevelsDownloadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue, vérifiez votre connection et réessayez !.
        /// </summary>
        public static string PopupLevelsDownloadTerminatedError {
            get {
                return ResourceManager.GetString("PopupLevelsDownloadTerminatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terminé !.
        /// </summary>
        public static string PopupLevelsDownloadTerminatedOk {
            get {
                return ResourceManager.GetString("PopupLevelsDownloadTerminatedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue modifiée. L&apos;application va quitter, veuillez redémarrer pour voir les changements..
        /// </summary>
        public static string RestartApplicationMessageText {
            get {
                return ResourceManager.GetString("RestartApplicationMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous avez actuellement un score de : #totalPoints points !.
        /// </summary>
        public static string ScoresPopupText {
            get {
                return ResourceManager.GetString("ScoresPopupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scores.
        /// </summary>
        public static string ScoresPopupTitle {
            get {
                return ResourceManager.GetString("ScoresPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activer les sons.
        /// </summary>
        public static string SettingsMenuActivateSound {
            get {
                return ResourceManager.GetString("SettingsMenuActivateSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer de langue.
        /// </summary>
        public static string SettingsMenuChangeLanguage {
            get {
                return ResourceManager.GetString("SettingsMenuChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contacter l&apos;auteur.
        /// </summary>
        public static string SettingsMenuContactAuthor {
            get {
                return ResourceManager.GetString("SettingsMenuContactAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désactiver les sons.
        /// </summary>
        public static string SettingsMenuDesactivateSound {
            get {
                return ResourceManager.GetString("SettingsMenuDesactivateSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comment jouer.
        /// </summary>
        public static string SettingsMenuHowToPlay {
            get {
                return ResourceManager.GetString("SettingsMenuHowToPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous préférez les films ?.
        /// </summary>
        public static string SettingsMenuMovieQuizzLink {
            get {
                return ResourceManager.GetString("SettingsMenuMovieQuizzLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proposer un pack.
        /// </summary>
        public static string SettingsMenuProposePack {
            get {
                return ResourceManager.GetString("SettingsMenuProposePack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quizz App.
        /// </summary>
        public static string SettingsMenuQuizzApp {
            get {
                return ResourceManager.GetString("SettingsMenuQuizzApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initialisation....
        /// </summary>
        public static string StartupInitializingMoviesStep1 {
            get {
                return ResourceManager.GetString("StartupInitializingMoviesStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Préparation des séries....
        /// </summary>
        public static string StartupInitializingMoviesStep2 {
            get {
                return ResourceManager.GetString("StartupInitializingMoviesStep2", resourceCulture);
            }
        }
    }
}
