// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using QuizzApp.Core.Helpers;

namespace QuizzApp.Core.Entities.Json
{
      

    public class LevelDl
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("value")]
        public int Value { get; set; }

        [JsonProperty("difficulty_id")]
        public int DifficultyId { get; set; }

        [JsonProperty("released")]
        public bool Released { get; set; }
        
        private long unixReleasedDateDate;
        [JsonProperty("release_date")]
        public long UnixReleasedDate
        {
            get { return unixReleasedDateDate; }
            set
            {
                if (unixReleasedDateDate != value)
                {
                    unixReleasedDateDate = value;
                    DateTime creationDate = DateTimeHelpers.FromUnixTime(unixReleasedDateDate);
                    this.ReleasedDate = creationDate;
                }
            }
        }
        public DateTime ReleasedDate { get; set; }

        [JsonProperty("md5")]
        public string Md5 { get; set; }

        [JsonProperty("zip_size")]
        public long ZipSize { get; set; }

        [JsonProperty("extra1")]
        public string Extra1 { get; set; }

        [JsonProperty("extra2")]
        public string Extra2 { get; set; }

        [JsonProperty("extra3")]
        public string Extra3 { get; set; }

        [JsonProperty("fextra1")]
        public float? Fextra1 { get; set; }

        [JsonProperty("fextra2")]
        public float? Fextra2 { get; set; }

        [JsonProperty("fextra3")]
        public float? Fextra3 { get; set; }

        [JsonProperty("packs")]
        public List<PackRep> Packs { get; set; } 

        [JsonProperty("language")]
        public string Language { get; set; }

        public LevelDl()
        {
            this.Packs = new List<PackRep>();
        }
    }


    public class PackRep
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("duplicated")]
        public bool Duplicated { get; set; }

        [JsonProperty("author")]
        public string Author { get; set; }

        [JsonProperty("level_id")]
        public int LevelId { get; set; }

        [JsonProperty("extra1")]
        public string Extra1 { get; set; }

        [JsonProperty("extra2")]
        public string Extra2 { get; set; }

        [JsonProperty("extra3")]
        public string Extra3 { get; set; }

        [JsonProperty("fextra1")]
        public float? Fextra1 { get; set; }

        [JsonProperty("fextra2")]
        public float? Fextra2 { get; set; }

        [JsonProperty("fextra3")]
        public float? Fextra3 { get; set; }

        [JsonProperty("difficulty")]
        public float? Difficulty { get; set; }
    }
}
